"""build models

Revision ID: f29cb5c1846b
Revises: 4baa6dea4051
Create Date: 2022-02-04 00:04:30.204370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29cb5c1846b'
down_revision = '4baa6dea4051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
